name: Build Android APK

# Perintah ini akan berjalan otomatis setiap kali ada perubahan di branch 'main'
on:
  push:
    branches:
      - main # Ganti menjadi 'master' jika default branch-mu adalah master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17' # Ubah ke '11' jika project kamu versi lama

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v5
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
